version: "3"
services:
  flavour-it-db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: P@ssword1
      MYSQL_DATABASE: flavour_it
      MYSQL_USER: kamhar
      MYSQL_PASSWORD: P@ssword1
    ports:
      - 3306:3306
  flavour-it-backend:
    build:
      dockerfile: ./docker/Dockerfile.dev
      context: ../flavour-it-backend
    volumes:
      - /app/node_modules
      - ../flavour-it-backend:/app
    ports:
      - 4000:4000
    restart: always
  flavour-it-frontend:
    build:
      dockerfile: ./docker/Dockerfile.dev
      context: ../flavour-it-frontend
    volumes:
      - /app/node_modules
      - ../flavour-it-frontend:/app
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
volumes:
  db_data: {}
