FROM node:14.15-alpine

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

COPY package*.json ./

RUN npm install && npm install react-scripts@3.4.1 -g

COPY . .

EXPOSE 3000
CMD [ "npm", "run", "start" ]
