FROM node:alpine

WORKDIR /app

COPY package*.json ./
COPY prisma ./prisma/

RUN npm install
RUN npm install -g @nestjs/cli
RUN npx prisma generate


COPY . .

EXPOSE 4000
CMD [ "npm", "run", "start:dev" ]
